baseurl = "https://jeffrey-kor.github.io/"
title = "Jeffrey 10 fingers"
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
sectionPagesMenu = "main"

[Author]
  name = "Jeffrey Yoon"
  bio = "Software Developer that's trying to contribute to society 🙈 Traveler with co-worker 🎌 Share, Reading, Talking🙆‍♂️"
  avatar = "avatar.jpg"

[Params]
  subtitle = "Jeffrey 10 fingers"
  description = "자유를 찾아가는 개발자"
  copyright = "Jeffrey"
  opengraph = true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  highlightColor = "blue" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "placeholder.png" # Logo image. Path relative to "static"
  title = "Jeffrey, Immerse, Learn and Archieve" # Logo title, otherwise will use site title
  subtitle = "Taking one more step in the footsteps of the seniors" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5
  tags_counter = true

[Params.widgets.social]
  linkedin = "JUNG-KI YOON"
  github = "Jeffrey-kor"
  email = "jeffrey.cofos"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
